/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
    export type MarketParamsStruct = {title: string, description: string, category: string, imageURI: string, creator: AddressLike, lockTime: BigNumberish, resolveTime: BigNumberish, feeBps: BigNumberish, protocolFeeShareBps: BigNumberish, outcomeNames: string[]}

    export type MarketParamsStructOutput = [title: string, description: string, category: string, imageURI: string, creator: string, lockTime: bigint, resolveTime: bigint, feeBps: bigint, protocolFeeShareBps: bigint, outcomeNames: string[]] & {title: string, description: string, category: string, imageURI: string, creator: string, lockTime: bigint, resolveTime: bigint, feeBps: bigint, protocolFeeShareBps: bigint, outcomeNames: string[] }
  

  export interface PredictionMarketInterface extends Interface {
    getFunction(nameOrSignature: "LP_TOKEN_ID" | "MAX_FEE_BPS" | "MAX_OUTCOMES" | "addFunding" | "balanceOf" | "balanceOfBatch" | "buy" | "calcBuy" | "calcSell" | "category" | "close" | "controller" | "createdAt" | "creator" | "description" | "exists" | "feeBps" | "getPrices" | "getReserves" | "imageURI" | "initialize" | "isApprovedForAll" | "lockTime" | "mergeSets" | "outcomeCount" | "outcomeName" | "pause" | "protocolFeeShareBps" | "redeem" | "removeFunding" | "resolve" | "resolveTime" | "safeBatchTransferFrom" | "safeTransferFrom" | "sell" | "setApprovalForAll" | "setTreasury" | "status" | "supportsInterface" | "title" | "totalSets" | "totalSupply()" | "totalSupply(uint256)" | "treasury" | "unpause" | "uri" | "voidMarket" | "winningOutcome"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApprovalForAll" | "Initialized" | "LiquidityAdded" | "LiquidityRemoved" | "MarketClosed" | "MarketPaused" | "MarketResolved" | "MarketUnpaused" | "MarketVoided" | "PredictionPlaced" | "PredictionSold" | "RewardClaimed" | "TransferBatch" | "TransferSingle" | "URI"): EventFragment;

    encodeFunctionData(functionFragment: 'LP_TOKEN_ID', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_OUTCOMES', values?: undefined): string;
encodeFunctionData(functionFragment: 'addFunding', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOfBatch', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'buy', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'calcBuy', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'calcSell', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'category', values?: undefined): string;
encodeFunctionData(functionFragment: 'close', values?: undefined): string;
encodeFunctionData(functionFragment: 'controller', values?: undefined): string;
encodeFunctionData(functionFragment: 'createdAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'creator', values?: undefined): string;
encodeFunctionData(functionFragment: 'description', values?: undefined): string;
encodeFunctionData(functionFragment: 'exists', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPrices', values?: undefined): string;
encodeFunctionData(functionFragment: 'getReserves', values?: undefined): string;
encodeFunctionData(functionFragment: 'imageURI', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, MarketParamsStruct]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'lockTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'mergeSets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'outcomeCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'outcomeName', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'protocolFeeShareBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'redeem', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeFunding', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolve', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeBatchTransferFrom', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'sell', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'status', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'title', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSets', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply()', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply(uint256)', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'uri', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'voidMarket', values?: undefined): string;
encodeFunctionData(functionFragment: 'winningOutcome', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'LP_TOKEN_ID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_OUTCOMES', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addFunding', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOfBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calcBuy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calcSell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'category', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'close', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'controller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createdAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'description', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReserves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'imageURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mergeSets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outcomeCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outcomeName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'protocolFeeShareBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeFunding', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeBatchTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'status', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'title', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply()', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply(uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voidMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'winningOutcome', data: BytesLike): Result;
  }

  
    export namespace ApprovalForAllEvent {
      export type InputTuple = [account: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [account: string, operator: string, approved: boolean];
      export interface OutputObject {account: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidityAddedEvent {
      export type InputTuple = [market: AddressLike, funder: AddressLike, amount: BigNumberish, lpShares: BigNumberish];
      export type OutputTuple = [market: string, funder: string, amount: bigint, lpShares: bigint];
      export interface OutputObject {market: string, funder: string, amount: bigint, lpShares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidityRemovedEvent {
      export type InputTuple = [market: AddressLike, provider: AddressLike, lpShares: BigNumberish];
      export type OutputTuple = [market: string, provider: string, lpShares: bigint];
      export interface OutputObject {market: string, provider: string, lpShares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketClosedEvent {
      export type InputTuple = [market: AddressLike];
      export type OutputTuple = [market: string];
      export interface OutputObject {market: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketPausedEvent {
      export type InputTuple = [market: AddressLike];
      export type OutputTuple = [market: string];
      export interface OutputObject {market: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketResolvedEvent {
      export type InputTuple = [market: AddressLike, winningOutcome: BigNumberish];
      export type OutputTuple = [market: string, winningOutcome: bigint];
      export interface OutputObject {market: string, winningOutcome: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketUnpausedEvent {
      export type InputTuple = [market: AddressLike];
      export type OutputTuple = [market: string];
      export interface OutputObject {market: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketVoidedEvent {
      export type InputTuple = [market: AddressLike];
      export type OutputTuple = [market: string];
      export interface OutputObject {market: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PredictionPlacedEvent {
      export type InputTuple = [market: AddressLike, buyer: AddressLike, outcome: BigNumberish, amountIn: BigNumberish, sharesOut: BigNumberish];
      export type OutputTuple = [market: string, buyer: string, outcome: bigint, amountIn: bigint, sharesOut: bigint];
      export interface OutputObject {market: string, buyer: string, outcome: bigint, amountIn: bigint, sharesOut: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PredictionSoldEvent {
      export type InputTuple = [market: AddressLike, seller: AddressLike, outcome: BigNumberish, sharesIn: BigNumberish, amountOut: BigNumberish];
      export type OutputTuple = [market: string, seller: string, outcome: bigint, sharesIn: bigint, amountOut: bigint];
      export interface OutputObject {market: string, seller: string, outcome: bigint, sharesIn: bigint, amountOut: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardClaimedEvent {
      export type InputTuple = [market: AddressLike, claimant: AddressLike, amount: BigNumberish];
      export type OutputTuple = [market: string, claimant: string, amount: bigint];
      export interface OutputObject {market: string, claimant: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferBatchEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[]];
      export type OutputTuple = [operator: string, from: string, to: string, ids: bigint[], values: bigint[]];
      export interface OutputObject {operator: string, from: string, to: string, ids: bigint[], values: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferSingleEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish];
      export type OutputTuple = [operator: string, from: string, to: string, id: bigint, value: bigint];
      export interface OutputObject {operator: string, from: string, to: string, id: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace URIEvent {
      export type InputTuple = [value: string, id: BigNumberish];
      export type OutputTuple = [value: string, id: bigint];
      export interface OutputObject {value: string, id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PredictionMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): PredictionMarket;
    waitForDeployment(): Promise<this>;

    interface: PredictionMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    LP_TOKEN_ID: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_OUTCOMES: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addFunding: TypedContractMethod<
      [minLpSharesOut: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    balanceOfBatch: TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >
    

    
    buy: TypedContractMethod<
      [outcomeIndex: BigNumberish, minSharesOut: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    calcBuy: TypedContractMethod<
      [outcomeIndex: BigNumberish, amountIn: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    calcSell: TypedContractMethod<
      [outcomeIndex: BigNumberish, returnAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    category: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    close: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    controller: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createdAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    creator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    description: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    exists: TypedContractMethod<
      [id: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    feeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPrices: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    getReserves: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    imageURI: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [controller_: AddressLike, treasury_: AddressLike, params: MarketParamsStruct, ],
      [void],
      'payable'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    lockTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mergeSets: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    outcomeCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    outcomeName: TypedContractMethod<
      [outcomeIndex: BigNumberish, ],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    protocolFeeShareBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    redeem: TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >
    

    
    removeFunding: TypedContractMethod<
      [lpShares: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolve: TypedContractMethod<
      [winningOutcome_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolveTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    safeBatchTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    safeTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    sell: TypedContractMethod<
      [outcomeIndex: BigNumberish, returnAmount: BigNumberish, maxSharesIn: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [treasury_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    status: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    title: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalSets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    "totalSupply()": TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    "totalSupply(uint256)": TypedContractMethod<
      [id: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    uri: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    voidMarket: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    winningOutcome: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'LP_TOKEN_ID'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_OUTCOMES'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addFunding'): TypedContractMethod<
      [minLpSharesOut: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOfBatch'): TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [outcomeIndex: BigNumberish, minSharesOut: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'calcBuy'): TypedContractMethod<
      [outcomeIndex: BigNumberish, amountIn: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calcSell'): TypedContractMethod<
      [outcomeIndex: BigNumberish, returnAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'category'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'close'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'controller'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createdAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'creator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'description'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'exists'): TypedContractMethod<
      [id: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'feeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPrices'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getReserves'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'imageURI'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [controller_: AddressLike, treasury_: AddressLike, params: MarketParamsStruct, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lockTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mergeSets'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'outcomeCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'outcomeName'): TypedContractMethod<
      [outcomeIndex: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'protocolFeeShareBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'redeem'): TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeFunding'): TypedContractMethod<
      [lpShares: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolve'): TypedContractMethod<
      [winningOutcome_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'safeBatchTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sell'): TypedContractMethod<
      [outcomeIndex: BigNumberish, returnAmount: BigNumberish, maxSharesIn: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [treasury_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'status'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'title'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply()'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply(uint256)'): TypedContractMethod<
      [id: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'uri'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'voidMarket'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'winningOutcome'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'LiquidityAdded'): TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
getEvent(key: 'LiquidityRemoved'): TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;
getEvent(key: 'MarketClosed'): TypedContractEvent<MarketClosedEvent.InputTuple, MarketClosedEvent.OutputTuple, MarketClosedEvent.OutputObject>;
getEvent(key: 'MarketPaused'): TypedContractEvent<MarketPausedEvent.InputTuple, MarketPausedEvent.OutputTuple, MarketPausedEvent.OutputObject>;
getEvent(key: 'MarketResolved'): TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
getEvent(key: 'MarketUnpaused'): TypedContractEvent<MarketUnpausedEvent.InputTuple, MarketUnpausedEvent.OutputTuple, MarketUnpausedEvent.OutputObject>;
getEvent(key: 'MarketVoided'): TypedContractEvent<MarketVoidedEvent.InputTuple, MarketVoidedEvent.OutputTuple, MarketVoidedEvent.OutputObject>;
getEvent(key: 'PredictionPlaced'): TypedContractEvent<PredictionPlacedEvent.InputTuple, PredictionPlacedEvent.OutputTuple, PredictionPlacedEvent.OutputObject>;
getEvent(key: 'PredictionSold'): TypedContractEvent<PredictionSoldEvent.InputTuple, PredictionSoldEvent.OutputTuple, PredictionSoldEvent.OutputObject>;
getEvent(key: 'RewardClaimed'): TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
getEvent(key: 'TransferBatch'): TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
getEvent(key: 'TransferSingle'): TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
getEvent(key: 'URI'): TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;

    filters: {
      
      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'LiquidityAdded(address,address,uint256,uint256)': TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
      LiquidityAdded: TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
    

      'LiquidityRemoved(address,address,uint256)': TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;
      LiquidityRemoved: TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;
    

      'MarketClosed(address)': TypedContractEvent<MarketClosedEvent.InputTuple, MarketClosedEvent.OutputTuple, MarketClosedEvent.OutputObject>;
      MarketClosed: TypedContractEvent<MarketClosedEvent.InputTuple, MarketClosedEvent.OutputTuple, MarketClosedEvent.OutputObject>;
    

      'MarketPaused(address)': TypedContractEvent<MarketPausedEvent.InputTuple, MarketPausedEvent.OutputTuple, MarketPausedEvent.OutputObject>;
      MarketPaused: TypedContractEvent<MarketPausedEvent.InputTuple, MarketPausedEvent.OutputTuple, MarketPausedEvent.OutputObject>;
    

      'MarketResolved(address,uint256)': TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
      MarketResolved: TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
    

      'MarketUnpaused(address)': TypedContractEvent<MarketUnpausedEvent.InputTuple, MarketUnpausedEvent.OutputTuple, MarketUnpausedEvent.OutputObject>;
      MarketUnpaused: TypedContractEvent<MarketUnpausedEvent.InputTuple, MarketUnpausedEvent.OutputTuple, MarketUnpausedEvent.OutputObject>;
    

      'MarketVoided(address)': TypedContractEvent<MarketVoidedEvent.InputTuple, MarketVoidedEvent.OutputTuple, MarketVoidedEvent.OutputObject>;
      MarketVoided: TypedContractEvent<MarketVoidedEvent.InputTuple, MarketVoidedEvent.OutputTuple, MarketVoidedEvent.OutputObject>;
    

      'PredictionPlaced(address,address,uint256,uint256,uint256)': TypedContractEvent<PredictionPlacedEvent.InputTuple, PredictionPlacedEvent.OutputTuple, PredictionPlacedEvent.OutputObject>;
      PredictionPlaced: TypedContractEvent<PredictionPlacedEvent.InputTuple, PredictionPlacedEvent.OutputTuple, PredictionPlacedEvent.OutputObject>;
    

      'PredictionSold(address,address,uint256,uint256,uint256)': TypedContractEvent<PredictionSoldEvent.InputTuple, PredictionSoldEvent.OutputTuple, PredictionSoldEvent.OutputObject>;
      PredictionSold: TypedContractEvent<PredictionSoldEvent.InputTuple, PredictionSoldEvent.OutputTuple, PredictionSoldEvent.OutputObject>;
    

      'RewardClaimed(address,address,uint256)': TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
      RewardClaimed: TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
    

      'TransferBatch(address,address,address,uint256[],uint256[])': TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
      TransferBatch: TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
    

      'TransferSingle(address,address,address,uint256,uint256)': TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
      TransferSingle: TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
    

      'URI(string,uint256)': TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
      URI: TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
    
    };
  }