/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
    export type MarketRecordStruct = {market: AddressLike, creator: AddressLike, title: string, category: string, status: BigNumberish, createdAt: BigNumberish, lockTime: BigNumberish, resolveTime: BigNumberish, outcomeCount: BigNumberish}

    export type MarketRecordStructOutput = [market: string, creator: string, title: string, category: string, status: bigint, createdAt: bigint, lockTime: bigint, resolveTime: bigint, outcomeCount: bigint] & {market: string, creator: string, title: string, category: string, status: bigint, createdAt: bigint, lockTime: bigint, resolveTime: bigint, outcomeCount: bigint }
  

    export type MarketParamsStruct = {title: string, description: string, category: string, imageURI: string, creator: AddressLike, lockTime: BigNumberish, resolveTime: BigNumberish, feeBps: BigNumberish, protocolFeeShareBps: BigNumberish, outcomeNames: string[]}

    export type MarketParamsStructOutput = [title: string, description: string, category: string, imageURI: string, creator: string, lockTime: bigint, resolveTime: bigint, feeBps: bigint, protocolFeeShareBps: bigint, outcomeNames: string[]] & {title: string, description: string, category: string, imageURI: string, creator: string, lockTime: bigint, resolveTime: bigint, feeBps: bigint, protocolFeeShareBps: bigint, outcomeNames: string[] }
  

  export interface PredictionFactoryInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_ROLE" | "BPS" | "DEFAULT_ADMIN_ROLE" | "MAX_FEE_BPS" | "activeMarkets" | "closeMarket" | "closedMarkets" | "countByStatus" | "createMarket" | "defaultFeeBps" | "defaultProtocolFeeShareBps" | "getRoleAdmin" | "grantRole" | "hasRole" | "marketAddress" | "marketAt" | "marketCount" | "marketImplementation" | "marketsByStatus" | "marketsPaged" | "pauseMarket" | "renounceRole" | "repointTreasury" | "resolveMarket" | "resolvedMarkets" | "revokeRole" | "setDefaultFees" | "setTreasury" | "supportsInterface" | "treasury" | "unpauseMarket" | "voidMarket"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FeesUpdated" | "MarketCreated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "TreasuryUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'activeMarkets', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'closeMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'closedMarkets', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'countByStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createMarket', values: [MarketParamsStruct]): string;
encodeFunctionData(functionFragment: 'defaultFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'defaultProtocolFeeShareBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'marketAddress', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'marketImplementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'marketsByStatus', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketsPaged', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'pauseMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'repointTreasury', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveMarket', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolvedMarkets', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setDefaultFees', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpauseMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'voidMarket', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activeMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closedMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'countByStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'defaultFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'defaultProtocolFeeShareBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketsByStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketsPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repointTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolvedMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDefaultFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpauseMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voidMarket', data: BytesLike): Result;
  }

  
    export namespace FeesUpdatedEvent {
      export type InputTuple = [feeBps: BigNumberish, protocolFeeShareBps: BigNumberish];
      export type OutputTuple = [feeBps: bigint, protocolFeeShareBps: bigint];
      export interface OutputObject {feeBps: bigint, protocolFeeShareBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketCreatedEvent {
      export type InputTuple = [marketId: BigNumberish, market: AddressLike, creator: AddressLike, category: string, outcomeCount: BigNumberish, initialFunding: BigNumberish];
      export type OutputTuple = [marketId: bigint, market: string, creator: string, category: string, outcomeCount: bigint, initialFunding: bigint];
      export interface OutputObject {marketId: bigint, market: string, creator: string, category: string, outcomeCount: bigint, initialFunding: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryUpdatedEvent {
      export type InputTuple = [treasury: AddressLike];
      export type OutputTuple = [treasury: string];
      export interface OutputObject {treasury: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PredictionFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): PredictionFactory;
    waitForDeployment(): Promise<this>;

    interface: PredictionFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MAX_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    activeMarkets: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >
    

    
    closeMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    closedMarkets: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >
    

    
    countByStatus: TypedContractMethod<
      [status: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    createMarket: TypedContractMethod<
      [params: MarketParamsStruct, ],
      [[bigint, string] & {marketId: bigint, market: string }],
      'payable'
    >
    

    
    defaultFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    defaultProtocolFeeShareBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    marketAddress: TypedContractMethod<
      [marketId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    marketAt: TypedContractMethod<
      [marketId: BigNumberish, ],
      [MarketRecordStructOutput],
      'view'
    >
    

    
    marketCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    marketImplementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    marketsByStatus: TypedContractMethod<
      [status: BigNumberish, offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >
    

    
    marketsPaged: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >
    

    
    pauseMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    repointTreasury: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolveMarket: TypedContractMethod<
      [marketId: BigNumberish, winningOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolvedMarkets: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setDefaultFees: TypedContractMethod<
      [feeBps: BigNumberish, protocolFeeShareBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [treasury_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unpauseMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    voidMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activeMarkets'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'closeMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closedMarkets'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'countByStatus'): TypedContractMethod<
      [status: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createMarket'): TypedContractMethod<
      [params: MarketParamsStruct, ],
      [[bigint, string] & {marketId: bigint, market: string }],
      'payable'
    >;
getFunction(nameOrSignature: 'defaultFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'defaultProtocolFeeShareBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'marketAddress'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'marketAt'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [MarketRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'marketCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'marketImplementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'marketsByStatus'): TypedContractMethod<
      [status: BigNumberish, offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'marketsPaged'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'pauseMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'repointTreasury'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveMarket'): TypedContractMethod<
      [marketId: BigNumberish, winningOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolvedMarkets'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDefaultFees'): TypedContractMethod<
      [feeBps: BigNumberish, protocolFeeShareBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [treasury_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unpauseMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voidMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FeesUpdated'): TypedContractEvent<FeesUpdatedEvent.InputTuple, FeesUpdatedEvent.OutputTuple, FeesUpdatedEvent.OutputObject>;
getEvent(key: 'MarketCreated'): TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'TreasuryUpdated'): TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;

    filters: {
      
      'FeesUpdated(uint16,uint16)': TypedContractEvent<FeesUpdatedEvent.InputTuple, FeesUpdatedEvent.OutputTuple, FeesUpdatedEvent.OutputObject>;
      FeesUpdated: TypedContractEvent<FeesUpdatedEvent.InputTuple, FeesUpdatedEvent.OutputTuple, FeesUpdatedEvent.OutputObject>;
    

      'MarketCreated(uint256,address,address,string,uint256,uint256)': TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
      MarketCreated: TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'TreasuryUpdated(address)': TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
      TreasuryUpdated: TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
    
    };
  }