/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPredictionFactory } from './IPredictionFactory.js';
export type { IPredictionMarket } from './IPredictionMarket.js';
export type { IPredictionTreasury } from './IPredictionTreasury.js';