/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
    export type MarketParamsStruct = {title: string, description: string, category: string, imageURI: string, creator: AddressLike, lockTime: BigNumberish, resolveTime: BigNumberish, feeBps: BigNumberish, protocolFeeShareBps: BigNumberish, outcomeNames: string[]}

    export type MarketParamsStructOutput = [title: string, description: string, category: string, imageURI: string, creator: string, lockTime: bigint, resolveTime: bigint, feeBps: bigint, protocolFeeShareBps: bigint, outcomeNames: string[]] & {title: string, description: string, category: string, imageURI: string, creator: string, lockTime: bigint, resolveTime: bigint, feeBps: bigint, protocolFeeShareBps: bigint, outcomeNames: string[] }
  

  export interface IPredictionMarketInterface extends Interface {
    getFunction(nameOrSignature: "addFunding" | "buy" | "calcBuy" | "calcSell" | "close" | "getPrices" | "getReserves" | "initialize" | "mergeSets" | "outcomeCount" | "pause" | "redeem" | "removeFunding" | "resolve" | "sell" | "setTreasury" | "status" | "unpause" | "voidMarket" | "winningOutcome"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'addFunding', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'buy', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'calcBuy', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'calcSell', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'close', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPrices', values?: undefined): string;
encodeFunctionData(functionFragment: 'getReserves', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, MarketParamsStruct]): string;
encodeFunctionData(functionFragment: 'mergeSets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'outcomeCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'redeem', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeFunding', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolve', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'sell', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'status', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'voidMarket', values?: undefined): string;
encodeFunctionData(functionFragment: 'winningOutcome', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addFunding', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calcBuy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calcSell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'close', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReserves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mergeSets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outcomeCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeFunding', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'status', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voidMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'winningOutcome', data: BytesLike): Result;
  }

  

  export interface IPredictionMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPredictionMarket;
    waitForDeployment(): Promise<this>;

    interface: IPredictionMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addFunding: TypedContractMethod<
      [minLpSharesOut: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    buy: TypedContractMethod<
      [outcomeIndex: BigNumberish, minSharesOut: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    calcBuy: TypedContractMethod<
      [outcomeIndex: BigNumberish, amountIn: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    calcSell: TypedContractMethod<
      [outcomeIndex: BigNumberish, returnAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    close: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getPrices: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    getReserves: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [controller: AddressLike, treasury: AddressLike, params: MarketParamsStruct, ],
      [void],
      'payable'
    >
    

    
    mergeSets: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    outcomeCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    redeem: TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >
    

    
    removeFunding: TypedContractMethod<
      [lpShares: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolve: TypedContractMethod<
      [winningOutcome_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    sell: TypedContractMethod<
      [outcomeIndex: BigNumberish, returnAmount: BigNumberish, maxSharesIn: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [treasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    status: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    voidMarket: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    winningOutcome: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addFunding'): TypedContractMethod<
      [minLpSharesOut: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [outcomeIndex: BigNumberish, minSharesOut: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'calcBuy'): TypedContractMethod<
      [outcomeIndex: BigNumberish, amountIn: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calcSell'): TypedContractMethod<
      [outcomeIndex: BigNumberish, returnAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'close'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPrices'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getReserves'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [controller: AddressLike, treasury: AddressLike, params: MarketParamsStruct, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'mergeSets'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'outcomeCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'redeem'): TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeFunding'): TypedContractMethod<
      [lpShares: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolve'): TypedContractMethod<
      [winningOutcome_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sell'): TypedContractMethod<
      [outcomeIndex: BigNumberish, returnAmount: BigNumberish, maxSharesIn: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [treasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'status'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voidMarket'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'winningOutcome'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }