/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
    export type MarketRecordStruct = {market: AddressLike, creator: AddressLike, title: string, category: string, status: BigNumberish, createdAt: BigNumberish, lockTime: BigNumberish, resolveTime: BigNumberish, outcomeCount: BigNumberish}

    export type MarketRecordStructOutput = [market: string, creator: string, title: string, category: string, status: bigint, createdAt: bigint, lockTime: bigint, resolveTime: bigint, outcomeCount: bigint] & {market: string, creator: string, title: string, category: string, status: bigint, createdAt: bigint, lockTime: bigint, resolveTime: bigint, outcomeCount: bigint }
  

    export type MarketParamsStruct = {title: string, description: string, category: string, imageURI: string, creator: AddressLike, lockTime: BigNumberish, resolveTime: BigNumberish, feeBps: BigNumberish, protocolFeeShareBps: BigNumberish, outcomeNames: string[]}

    export type MarketParamsStructOutput = [title: string, description: string, category: string, imageURI: string, creator: string, lockTime: bigint, resolveTime: bigint, feeBps: bigint, protocolFeeShareBps: bigint, outcomeNames: string[]] & {title: string, description: string, category: string, imageURI: string, creator: string, lockTime: bigint, resolveTime: bigint, feeBps: bigint, protocolFeeShareBps: bigint, outcomeNames: string[] }
  

  export interface IPredictionFactoryInterface extends Interface {
    getFunction(nameOrSignature: "activeMarkets" | "closeMarket" | "closedMarkets" | "createMarket" | "marketAddress" | "marketAt" | "marketCount" | "marketsByStatus" | "marketsPaged" | "pauseMarket" | "resolveMarket" | "resolvedMarkets" | "setDefaultFees" | "setTreasury" | "treasury" | "unpauseMarket" | "voidMarket"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'activeMarkets', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'closeMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'closedMarkets', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createMarket', values: [MarketParamsStruct]): string;
encodeFunctionData(functionFragment: 'marketAddress', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'marketsByStatus', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketsPaged', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'pauseMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveMarket', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolvedMarkets', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDefaultFees', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpauseMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'voidMarket', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'activeMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closedMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketsByStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketsPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolvedMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDefaultFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpauseMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voidMarket', data: BytesLike): Result;
  }

  

  export interface IPredictionFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPredictionFactory;
    waitForDeployment(): Promise<this>;

    interface: IPredictionFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activeMarkets: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >
    

    
    closeMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    closedMarkets: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >
    

    
    createMarket: TypedContractMethod<
      [params: MarketParamsStruct, ],
      [[bigint, string] & {marketId: bigint, market: string }],
      'payable'
    >
    

    
    marketAddress: TypedContractMethod<
      [marketId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    marketAt: TypedContractMethod<
      [marketId: BigNumberish, ],
      [MarketRecordStructOutput],
      'view'
    >
    

    
    marketCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    marketsByStatus: TypedContractMethod<
      [status: BigNumberish, offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >
    

    
    marketsPaged: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >
    

    
    pauseMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolveMarket: TypedContractMethod<
      [marketId: BigNumberish, winningOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolvedMarkets: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >
    

    
    setDefaultFees: TypedContractMethod<
      [feeBps: BigNumberish, protocolFeeShareBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [treasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unpauseMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    voidMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activeMarkets'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'closeMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closedMarkets'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'createMarket'): TypedContractMethod<
      [params: MarketParamsStruct, ],
      [[bigint, string] & {marketId: bigint, market: string }],
      'payable'
    >;
getFunction(nameOrSignature: 'marketAddress'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'marketAt'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [MarketRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'marketCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'marketsByStatus'): TypedContractMethod<
      [status: BigNumberish, offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'marketsPaged'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'pauseMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveMarket'): TypedContractMethod<
      [marketId: BigNumberish, winningOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolvedMarkets'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [MarketRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'setDefaultFees'): TypedContractMethod<
      [feeBps: BigNumberish, protocolFeeShareBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [treasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unpauseMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voidMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }