/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPredictionFactory__factory } from './IPredictionFactory__factory.js';
export { IPredictionMarket__factory } from './IPredictionMarket__factory.js';
export { IPredictionTreasury__factory } from './IPredictionTreasury__factory.js';