// The app's icon vocabulary: every icon the UI may render, imported ONCE from lucide's node
// data and named in the app's own kebab voice. Components never import lucide directly -
// the registry is what keeps the bundle to the icons on this list.

import
{
    Activity,
    ArrowDownUp,
    ArrowLeft,
    ArrowRight,
    ArrowUpRight,
    BadgeCheck,
    Bell,
    Bitcoin,
    Bookmark,
    CalendarDays,
    ChartLine,
    ChartNoAxesColumn,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsLeft,
    ChevronsRight,
    CircleCheck,
    CircleHelp,
    CircleX,
    Clapperboard,
    Clock,
    Compass,
    Copy,
    Cpu,
    CreditCard,
    Crown,
    DollarSign,
    Dumbbell,
    ExternalLink,
    FileText,
    Flame,
    FlaskConical,
    Gavel,
    Globe,
    House,
    Info,
    Landmark,
    Languages,
    LogOut,
    Mail,
    Medal,
    Menu,
    MessageCircle,
    MessagesSquare,
    Minus,
    Moon,
    Plus,
    Search,
    Pencil,
    Send,
    Settings,
    Share2,
    SlidersHorizontal,
    Sparkles,
    Sun,
    Tag,
    Trash2,
    TrendingDown,
    TrendingUp,
    TriangleAlert,
    Trophy,
    User,
    Users,
    Wallet,
    X,
    type IconNode
} from 'lucide';

export const ICONS = {
    'activity': Activity,
    'alert': TriangleAlert,
    'arrow-left': ArrowLeft,
    'arrow-right': ArrowRight,
    'arrow-up-right': ArrowUpRight,
    'bell': Bell,
    'bookmark': Bookmark,
    'calendar': CalendarDays,
    'chart': ChartLine,
    'check': Check,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'chevron-up': ChevronUp,
    'chevrons-left': ChevronsLeft,
    'chevrons-right': ChevronsRight,
    'circle-check': CircleCheck,
    'circle-x': CircleX,
    'clock': Clock,
    'comments': MessageCircle,
    'compass': Compass,
    'copy': Copy,
    'crown': Crown,
    'deposit': CreditCard,
    'external': ExternalLink,
    'filters': SlidersHorizontal,
    'flame': Flame,
    'gavel': Gavel,
    'globe': Globe,
    'help': CircleHelp,
    'holders': Users,
    'home': House,
    'info': Info,
    'language': Languages,
    'log-out': LogOut,
    'mail': Mail,
    'medal': Medal,
    'menu': Menu,
    'messages': MessagesSquare,
    'minus': Minus,
    'moon': Moon,
    'plus': Plus,
    'rules': FileText,
    'search': Search,
    'send': Send,
    'edit': Pencil,
    'settings': Settings,
    'share': Share2,
    'sort': ArrowDownUp,
    'sparkles': Sparkles,
    'sun': Sun,
    'tag': Tag,
    'trash': Trash2,
    'trending-down': TrendingDown,
    'trending-up': TrendingUp,
    'trophy': Trophy,
    'user': User,
    'verified': BadgeCheck,
    'volume': ChartNoAxesColumn,
    'wallet': Wallet,
    'x': X,

    'cat-crypto': Bitcoin,
    'cat-culture': Clapperboard,
    'cat-economy': DollarSign,
    'cat-politics': Landmark,
    'cat-science': FlaskConical,
    'cat-sports': Dumbbell,
    'cat-tech': Cpu,
    'cat-world': Globe
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof ICONS;

/**
 * Icons that imply reading direction and must flip under RTL. Trend arrows stay: a rising
 * market points up-right in both directions. External-link stays per platform convention.
 */
export const MIRRORED: ReadonlySet<IconName> = new Set<IconName>([
    'arrow-left',
    'arrow-right',
    'chevron-left',
    'chevron-right',
    'chevrons-left',
    'chevrons-right',
    'log-out'
]);
