/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from './interfaces/index.js';
export * as mocks from './mocks/index.js';
export { PredictionFactory__factory } from './PredictionFactory__factory.js';
export { PredictionMarket__factory } from './PredictionMarket__factory.js';
export { PredictionTreasury__factory } from './PredictionTreasury__factory.js';