/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ReentrantBuyerInterface extends Interface {
    getFunction(nameOrSignature: "armed" | "attackBuy" | "attackRedeem" | "attackSell" | "market" | "onERC1155BatchReceived" | "onERC1155Received" | "reenteredSuccessfully" | "supportsInterface"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'armed', values?: undefined): string;
encodeFunctionData(functionFragment: 'attackBuy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'attackRedeem', values?: undefined): string;
encodeFunctionData(functionFragment: 'attackSell', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'market', values?: undefined): string;
encodeFunctionData(functionFragment: 'onERC1155BatchReceived', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'onERC1155Received', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'reenteredSuccessfully', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'armed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attackBuy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attackRedeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attackSell', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'market', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC1155BatchReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC1155Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reenteredSuccessfully', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
  }

  

  export interface ReentrantBuyer extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReentrantBuyer;
    waitForDeployment(): Promise<this>;

    interface: ReentrantBuyerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    armed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    attackBuy: TypedContractMethod<
      [outcomeIndex: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    attackRedeem: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    attackSell: TypedContractMethod<
      [outcomeIndex: BigNumberish, returnAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    market: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    onERC1155BatchReceived: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish[], arg3: BigNumberish[], arg4: BytesLike, ],
      [string],
      'view'
    >
    

    
    onERC1155Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'view'
    >
    

    
    reenteredSuccessfully: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'armed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'attackBuy'): TypedContractMethod<
      [outcomeIndex: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'attackRedeem'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'attackSell'): TypedContractMethod<
      [outcomeIndex: BigNumberish, returnAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'market'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'onERC1155BatchReceived'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish[], arg3: BigNumberish[], arg4: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'onERC1155Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reenteredSuccessfully'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }